### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Tanianatania** [Tanianatania/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by VolodymyrVerm** [comment]
One of the popular English actor and film producer is named as Jason Statham . He is well known American celebrity. He is famous for contribution to professional life. He is very talented and skilled actor. He is famous for his action thriller roles and portraying tough, irredeemable, and Machiavellian characters. He was featured in many movies. Some of them are The Fate of the Furious in 2017, Furious 7 in 2015 and many more.
