### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Tanianatania** [Tanianatania/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by VolodymyrVerm** [comment]
https://www.instagram.com/jasonstatham/?hl=eng
https://www.facebook.com/pg/JasonStatham/about/?ref=page_internal
https://twitter.com/realjstatham
+94 75 230 0479
