### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Tanianatania** [Tanianatania/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by VolodymyrVerm** [comment]
Affairs
Jason is single. He is not married yet but he is in a relationship with Rosie Huntington Whiteley, his girlfriend. She is a model. They announced their engagement in January 2016. The couple is blessed with a son named Jack Oscar Statham born on 24th June 2017. They seem to be very happy with each other. The couple makes public appearances together often. There is no any sign of Separation between them. They are living peacefully.

Net Worth
This excellent actor makes good money from his work. The net worth of Jason is estimated to have $40 million in 2018. His salary is kept in privacy but there is no doubt in the mind of his supporters and followers he is satisfied with his earning.

Hobby
The eminent actor adores Jet Skiing, and has been spotted a number of times riding a Jet Ski. The actor was recently seen playing with the waves, riding a Jet Ski with his girlfriend Rosie Huntington-Whiteley, in the marvelous vacation destination St. Barts. Jason’s love for water sport activities is evident from the fact that he was also an active member of Britain’s National Diving Squad for almost twelve years.
